"""add_due_date_to_billings

Revision ID: 9547d90e5eed
Revises: k8m6n0f2o5p4
Create Date: 2026-04-20 16:09:28.671393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9547d90e5eed'
down_revision: Union[str, None] = 'k8m6n0f2o5p4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_active_appointments'), table_name='appointments')
    op.add_column('billings', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('billings', 'appointment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_billing_paid_at'), table_name='billings')
    op.drop_constraint(op.f('uq_billing_appointment'), 'billings', type_='unique')
    op.create_index('uq_billing_appointment', 'billings', ['appointment_id'], unique=True, postgresql_where=sa.text('appointment_id IS NOT NULL'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_billing_appointment', table_name='billings', postgresql_where=sa.text('appointment_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_billing_appointment'), 'billings', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_billing_paid_at'), 'billings', ['paid_at'], unique=False)
    op.alter_column('billings', 'appointment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('billings', 'due_date')
    op.create_index(op.f('idx_active_appointments'), 'appointments', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
