export {
  loginSchema,
  patientSchema,
  appointmentSchema,
  billingSchema,
  doctorSchema,
  patientSignupSchema,
  doctorSignupSchema,
  resetPasswordSchema,
  type LoginFormData,
  type PatientFormData,
  type PatientFormInput,
  type AppointmentFormData,
  type AppointmentFormInput,
  type BillingFormData,
  type BillingFormInput,
  type DoctorFormData,
  type DoctorFormInput,
  type PatientSignupFormData,
  type PatientSignupFormInput,
  type DoctorSignupFormData,
  type DoctorSignupFormInput,
  type ResetPasswordFormData,
} from './schemas';
