export {
  loginSchema,
  patientSchema,
  appointmentSchema,
  billingSchema,
  doctorSchema,
  type LoginFormData,
  type PatientFormData,
  type PatientFormInput,
  type AppointmentFormData,
  type AppointmentFormInput,
  type BillingFormData,
  type BillingFormInput,
  type DoctorFormData,
  type DoctorFormInput,
} from './schemas';
